### PR TITLE
spreadable TextStyles again

### PR DESCRIPTION
**Pull request by sebllll**
missed that one when changing https://github.com/mrvux/dx11-vvvv/pull/272#issuecomment-259166048

### CODE REVIEW

**Comment by ethermammoth** [comment]
Hey think something is still missing
Checkout TextLayoutAdvancedNode.cs from line 89
Think it needs some bin sizing

**Comment by sebllll** [comment]
hm, the input is a ISpread<ISpread<ITextStyler>> do you have a patch that is not working or producing strange behaviour?

**Comment by ethermammoth** [comment]
Ok maybe i have missed something- but when i try to input a spread of text - and try to style the text with multiple styles using cons - i want to be able to be able to color and format each slice of text with multiple style nodes. 
[TextSpreaded.zip](https://github.com/mrvux/dx11-vvvv/files/588656/TextSpreaded.zip)

**Comment by sebllll** [comment]
ok, this should now work.

for your usecase you can't use a cons, but the fresh zip (textStyle)

image

**Comment by ethermammoth** [comment]
superb thanks!

**Comment by mrvux** [comment]
Bit late in the discussion, but all seems good, so will merge, thanks!

**Pull request merged**
