### PR TITLE
PreferTechnique layer node and some changes to semantics.

### PR DESCRIPTION
**Pull request by dotprodukt**

### CODE REVIEW

**Comment by dotprodukt** [comment]
hold off on this, more significant changes to semantics have happened that have yet to be pushed.

**Comment by mrvux** [comment]
Thanks for pull request,
for next ones, what would be nice tho would be to split those into smaller ones tho, so it's a bit easier to comment and merge what's relevant.
* Aggregating semantic and additional types (eg: float2[] and Texture2DMSArray) can be merged right away.
* Preferred technique can probably also be merged, I don't think anyone is even using that, was likely a test for some deferred setup), so in any case this will never be much of a breaking change if so.
* https://github.com/dotprodukt/dx11-vvvv/commit/3f989d616d9ca4b6057fdecb5ad205c37bf8e03b  is bit different, as setting Texture2DArray to texture2d shader input is generally allowed by cards (they will take first slice and in general send a runtime warning). Since it can be a reasonable breaking change on some setups I would keep this one as is (actually could make the node send a warning instead of defaulting to null).

I can try that part already, and merge for now (while just only reverting the last mentioned null binding).

**Comment by dotprodukt** [comment]
So the reasoning behind preventing textures with more than a single array slice from being bound on a semantic for a non-array type (even though it is allowed) is because of what the semantic is trying to hint about the relationship between the input resource and the shaders upstream of where the semantic is applied.  Also, because the texture2d semantic can also bind to a Texture2DArray (which is also valid), this made the texture2dArray semantic redundant and lose the meaning it is meant to convey.

Really it's just about avoiding ambiguity.  Though I do agree that it should send a warning instead of not setting the resource at all.

Actually most of the above commits for semantic stuff has changed a lot on my local to allow for arrays of all the types we currently can pass in.  So being able to use a semantic on something like float4[n] or Texture2D[n] instead of a Texture2DArray (which allows for varied formats and sizes among the collection).  Another good example off the top of my head would be float4[9] which could be an array of SH coefficients and everyone upstream can use that for ambient diffuse lighting.  Technically you could just put this kind of data in a structured buffer and your good to go but there are many cases where I just don't think that is a good idea depending on how you access the data.  Also, anything we can pass in on pins, we should be able to bind via semantics.

**Comment by smakhtin** [comment]
I not so deep in this discussion, but i agree that having array semantic in shader would be great for our work as well. As we discussed with @mrvux we now using Texture2DArray, but you need to convert a spread of textures into it, which is not so idiomatic for vvvv.

**Comment by mrvux** [comment]
Yeah I'm totally fine with all the array types and will hapilly get those as pull requests.

Passign SH coeff is better as array since you'll have a cbuffer storage (which is a bit more efficient than  structured buffers in some cases).

For texture array I'd still rather send a warning, actually there's much worse cases that are also allowed now and which should set a null (like passing a uint texture on a slot used by a sampler is allowed but guaranteed crash in many drivers).

Arrays of textures and texturesArrays (at least in dx11, different story in dx12 now), is a different thing still, as in dx11 Array of textures doesn't exist, so you're not allowed to do dynamic indexing, so they totally serve different purpoeses.

**Comment by dotprodukt** [comment]
You can have arrays of textures and no you cannot do dynamic indexing but you can do constant indexing which is still totally worth it.  In a loop (unrolled only) you can have a dynamic upper bound, so you can iterate over a subrange of the array.  Generally the compiler doesn't handle this very well and puts out sub optimal code but I still think it's worth it if not used excessively in a shader and with a appropriate number of textures (we have a small number of slots for them anyway).

Something else I've still been debating with myself is if the array semantics should also provide the binsize to the shader?  So an array semantic for SOMEARRAY could also check for the existance of and set that value on an scalar variable having the semantic SOMEARRAY_BINSIZE.  Or something like that.  Technically the user could just use a separate semantic node for that purpose.  A problem with assuming that the user will somehow know if a shader will require that additional semantic, is that the shader could have been written by somebody else.

This would be a bit different from what happens on pins.  When we expose an array that way, we generate the additional bin size pin but currently there is no way to get that value in the shader unless you make your own pin for it, which is one too many in my mind.  So should we do something similar for pins too?  Some way for the user to say that they want that information?

**Comment by mrvux** [comment]
Yeah that's fine by me, I'll test pull request tomorrow and merge it, i'll just likely change the little bit to send warning instead.

For array of textures yeah I use them from time to time, can be quite useful and it's not very common that I go past the 128 shader view limit (as opposite to the 8 uav limit which I pass quite often nowadays, but got a sharpdx device override around so now i got 64 ;)

For bin size versions since they are new nodes it won't hurt, so totally happy to merge those when they pop in.

Once additional thing which is in my list is to also allow to expose constant buffer as pin/semantic directly (so we can pack some common data and avoid to upload several times), but that needs some changes in the reflector.

**Comment by mrvux** [comment]
Thanks, this is now merged, as mentioned only change I will apply is to remove array size check.

**Comment by dotprodukt** [comment]
Sorry was taken away from this for a few days.  Got up to date with all your changes and trying to finish up the semantics for array types.  There were a a few things about how I was passing around data I wasn't comfortable with so my initial implementation is changing a bit.

**Pull request merged**
